apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  namespace: ricky
spec:
  selector:
    matchLabels:
      app: report
  replicas: 1
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
        - name: report
          image: yshua5631/report:0.0.1
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 80 #容器开放的端口，即使是80也要显示指定
            - containerPort: 443 # 也开放了https端口
---

apiVersion: v1
kind: Service
metadata:
  name: report-svc
  namespace: ricky
spec:
  ports:
    - port: 8080 # 集群内部可以访问的端口. 备注  -p 20180:80， 80代表容器端口，20180代表主机端口
      targetPort: 8080 # Docker实例的端口 - 最保守的
      #nodePort: 31280  # 暴露给外网的端口
      protocol: TCP
      name: http
  # type: NodePort # k8s会向外网暴露端口，如果是在阿里云上，阿里云需要将相应的端口设置成白名单
  selector:
    app: report
